export const AUTH_USER_REQUESTED = 'AUTH_USER_REQUESTED';
export const AUTH_USER_RECEIVED = 'AUTH_USER_RECEIVED';
export const AUTH_USER_REJECTED = 'AUTH_USER_REJECTED';

export const LOGOUT_REQUESTED = 'LOGOUT_REQUESTED';