export const AUTH_USER_REQUESTED = 'AUTH_USER_REQUESTED';
export const AUTH_USER_RECEIVED = 'AUTH_USER_RECEIVED';
export const AUTH_USER_REJECTED = 'AUTH_USER_REJECTED';

export const LOGOUT_REQUESTED = 'LOGOUT_REQUESTED';

export const GET_ALL_COUNTRIES_REQUESTED = 'GET_ALL_COUNTRIES_REQUESTED';
export const GET_ALL_COUNTRIES_RECEIVED = 'GET_ALL_COUNTRIES_RECEIVED';
export const GET_ALL_COUNTRIES_REJECTED = 'GET_ALL_COUNTRIES_REJECTED';

export const TOGGLE_POPUP_STATUS = 'TOGGLE_POPUP_STATUS';
